version: "3.9"

include:
  - docker-compose.dependencies.yml

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/norman-k-backend:${IMAGE_TAG}

    ports:
      - "127.0.0.1:${SPRING_PUBLIC_PORT}:${SPRING_PRIVATE_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://db:5432/${POSTGRE_DATABASE_NAME}?useSSL=false",
        "spring.datasource.username": "${POSTGRE_USER}",
        "spring.datasource.password": "${POSTGRE_PASSWORD}",
        "spring.liquibase.enabled": true,
        "spring.liquibase.change-log": "classpath:db/changelog-master.yaml"
      }'
