name: Continuous Deployment

on:
  workflow_call:

# All continuous deployment jobs should be defined here
# They will run after all the CI jobs are completed successfully
jobs:

  deploy-backend:
    name: Deploy Backend
    concurrency: ${{ github.ref_name }}-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Placeholder for deploy step
        run: echo "No deploy step defined. Skipping."
