name: Scheduled - Daily check for vulnerable dependencies
on:
  schedule:
    - cron: "17 7 * * *"
  workflow_dispatch:

env:
  PROJECT_DIR: ${{ github.workspace }}/api
  MAVEN_OPTS: "-Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --fail-at-end"

jobs:

  dependency-security-update-database:
    name: Daily update of vulnerabilities database
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Download Dependency Check Database
        uses: ./.github/actions/download-dependency-check-database
        with:
          database-directory: ${{ env.PROJECT_DIR }}/dependency-check-database
          nvdApiKey: ${{ secrets.NVD_API_KEY }}
          project-directory: ${{ env.PROJECT_DIR }}

  dependency-security-check:
    name: Daily check for vulnerable dependencies
    runs-on: ubuntu-24.04
    needs: dependency-security-update-database
    defaults:
      run:
        shell: bash
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Download Dependency Check Database
        uses: ./.github/actions/download-dependency-check-database
        with:
          database-directory: ${{ env.PROJECT_DIR }}/dependency-check-database
          nvdApiKey: ${{ secrets.NVD_API_KEY }}
          project-directory: ${{ env.PROJECT_DIR }}

      - name: Run vulnerability check on all dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ./mvnw $MAVEN_CLI_OPTS -DdataDirectory=$PROJECT_DIR/dependency-check-database dependency-check:check

      - name: Upload vulnerable dependencies report
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: vulnerable-dependencies-report
          retention-days: "1"
          path: |
            ${{ env.PROJECT_DIR }}/target/dependency-check-report.html
