name: FrontEnd CI/CD

on:
  push:
    branches: ["feature/backend-ci-cd"]
    paths:
      - "backend/**"
      - ".github/workflows/backend*"
  pull_request:
    branches: ["feature/backend-ci-cd"]
    paths:
      - "backend/**"
      - ".github/workflows/backend*"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend_ci:
    name: BackEnd CI
    uses: ./.github/workflows/backend_ci.yml
    secrets: inherit

  backend_cd:
    name: BackEnd CD
    needs: backend_ci
    # if: false # Change this condition when you want to enable CD (eg: `if: github.event_name != 'pull_request'`)
    uses: ./.github/workflows/backend_cd.yml
    secrets: inherit
